"""The master slide library for office interior design presentations.

Every row names a real `SlideLayout` and `SlideStyleKind` from
src/types/slide.ts, so the rules engine emits slides Presenta's renderer
already understands. Rows whose layout is a poor fit are flagged in `notes`
with "GAP:" and roll up into the Layout Coverage tab.

Field order in SLIDE_ROWS
-------------------------
 0 id              stable slug, safe to persist in a template definition
 1 section         one of SECTIONS below
 2 name            the slide's name in the library UI
 3 purpose         why this slide exists at all — the job it does in the pitch
 4 title           suggested on-slide title ({tokens} are filled from project data)
 5 content         what actually goes on the slide
 6 layout          a real SlideLayout value
 7 style           a real SlideStyleKind value
 8 required_inputs assets/data without which the slide cannot be built
 9 optional_inputs assets/data that improve it
10 baseline        M | R | O  — before typology/concept adjustment
11 pillar          a DESIGN_PILLARS id from src/lib/conceptLibrary.ts, or ""
12 concepts        space-separated concept ids within that pillar, or ""
13 notes           authoring guidance; "GAP:" marks a missing layout

`baseline` is the default only. Tab 05 (typology) and tab 06 (concept) raise
or lower it per project, and the Rules tab defines precedence.
"""

SECTIONS = [
    ("00", "Cover & Credentials", "Who we are and why we are in the room"),
    ("01", "Understanding the Brief", "Proving we listened before we designed"),
    ("02", "Site & Context", "What we are working with"),
    ("03", "Strategy & Concept", "The idea that governs every later decision"),
    ("04", "Planning", "The idea, resolved into a plan that holds up"),
    ("05", "Design - Space by Space", "What it will actually feel like"),
    ("06", "Materials & Detail", "What it is made of"),
    ("07", "Technical & Compliance", "Why it will work and pass"),
    ("08", "Commercials & Delivery", "What it costs and how it gets built"),
]

FIELDS = [
    "id", "section", "name", "purpose", "title", "content", "layout", "style",
    "required_inputs", "optional_inputs", "baseline", "pillar", "concepts", "notes",
]

# ---------------------------------------------------------------------------

SLIDE_ROWS = [

    # === 00 · Cover & Credentials ==========================================
    ("S001", "00", "Cover / Title",
     "Establish whose deck this is, for whom, and when — the slide that stays on screen while people settle in.",
     "{client_name}", "Client name, project descriptor, both logos, date, a hero image or looping render of the space.",
     "title-slide", "section-starter",
     "Client name; project name; date; client logo", "Hero image or hero video; accent colour pulled from the logo",
     "M", "", "",
     "Accent colour should already be derived from the client logo at project creation."),

    ("S002", "00", "Agenda / Contents",
     "Tell the room how long this will take and when their part comes up, so nobody interrupts early.",
     "What we will cover", "5-7 numbered sections matching the deck's own section dividers, with an approximate timing.",
     "title-content", "standard",
     "Final section list", "Timings; named presenter per section",
     "R", "", "",
     "Generate from the sections actually present after rules run — never hardcode."),

    ("S003", "00", "About Us",
     "Establish that the firm can carry a project of this size before any design opinion is offered.",
     "About {brand_name}", "Positioning line, what we do end-to-end, scale markers, delivery footprint.",
     "title-content", "company",
     "Brand (OB / SKV / both)", "Founding year; office locations; team size",
     "M", "", "",
     "Auto-populate from the brand profile — this is the brand-driven auto-population ask."),

    ("S004", "00", "Credentials by Numbers",
     "Convert the claim in the previous slide into figures that can be checked.",
     "By the numbers", "3-4 stats: sq ft delivered, projects completed, cities, average handover variance.",
     "title-stats", "company",
     "Credential figures for the brand", "Figures filtered to this typology",
     "O", "economics-operations", "operational-efficiency",
     "Filter to the project's own typology where the data supports it — a GCC client wants GCC numbers."),

    ("S005", "00", "Client Logo Wall",
     "Borrow credibility from recognisable names, especially ones in the same typology.",
     "Who we build for", "A grid of 12-24 client logos, ideally sorted so same-typology clients lead.",
     "title-content", "company",
     "Client logo files", "Per-logo typology tag for filtering",
     "O", "", "",
     "GAP: no logo-wall layout. A grid layout is needed; freeform works but every logo must be placed by hand."),

    ("S006", "00", "Our Team",
     "Put names and faces to the people the client will actually deal with.",
     "Your team", "4-8 people: photo, name, role, one line of relevant experience.",
     "title-content", "standard",
     "Team photos; names; roles", "Per-person relevant project credits",
     "O", "", "",
     "GAP: no team-grid layout. freeform can do it but is manual."),

    ("S007", "00", "Why Us / Differentiators",
     "Answer the unspoken comparison against the two other firms pitching this week.",
     "Why {brand_name}", "3-5 differentiators, each one line, converging on a single outcome statement.",
     "merge-diagram", "standard",
     "Differentiator list", "Proof point per differentiator",
     "O", "economics-operations", "operational-efficiency",
     "Differentiators should be typology-specific — 'we do GCCs' beats 'we are detail-oriented'."),

    ("S008", "00", "Selected Work / Case Study",
     "Show one comparable project in enough depth to be believed, rather than ten in a blur.",
     "{case_study_name}", "One project: brief, what was solved, 2-3 images, outcome figure.",
     "concept", "design",
     "Case study images; project facts", "Client quote; before/after pair",
     "R", "", "",
     "Pick by typology match first, then by scale. Same-typology beats same-city."),

    # === 01 · Understanding the Brief ======================================
    ("S010", "01", "Section Divider - Understanding",
     "Mark the shift from credentials to the client's own project.",
     "Understanding the brief", "Numeral, section title, one-line framing question.",
     "title-slide", "section-starter", "Section number", "",
     "R", "people", "",
     "Reuses pillarSectionSlide() in src/lib/conceptSlides.ts."),

    ("S011", "01", "Brief Recap / Mandate",
     "Repeat the brief back in the client's own words — the cheapest way to prove you listened and to surface a misunderstanding while it is still free.",
     "The brief", "What was asked for, the constraints given, the success criteria, in the client's phrasing.",
     "title-content", "standard",
     "Brief document or meeting notes", "Direct quotes from the briefing",
     "M", "people", "user-profiles",
     "Quote the client verbatim where possible. Paraphrase reads as interpretation."),

    ("S012", "01", "Project Snapshot",
     "Put every number the whole room must agree on in one place, early.",
     "Project at a glance", "Area, headcount, floors, location, target handover, budget band.",
     "title-stats", "standard",
     "Area; headcount; location; timeline", "Budget band; number of floors",
     "M", "space-planning", "capacity-density",
     "If any figure here is wrong, everything downstream is wrong. Present it for confirmation."),

    ("S013", "01", "Brand Landscape",
     "Extract the client's visual and cultural vocabulary so later design moves can be traced back to it rather than to taste.",
     "Understanding {client_name}",
     "Brand palette, logo usage, tone, product/service imagery, existing spatial cues.",
     "freeform", "standard",
     "Client brand guidelines; brand imagery", "Existing office photos; product imagery",
     "R", "experience-brand", "brand-expression storytelling",
     "The E-Com Express reference slide is exactly this pattern — see ECOM_SLIDE_2_ELEMENTS."),

    ("S014", "01", "Workplace Aspirations",
     "Name what the client wants the workplace to do for them, in their words, before proposing how.",
     "What do you aspire for at your workplace?",
     "6-8 aspiration statements as cards or icons, drawn from the briefing or a staff survey.",
     "freeform", "standard",
     "Aspiration statements", "Staff survey results; leadership interview quotes",
     "R", "people", "employee-experience work-styles",
     "Pattern exists as ECOM_SLIDE_1_ELEMENTS. Survey-backed statements carry far more weight than assumed ones."),

    ("S015", "01", "User Profiles / Personas",
     "Make the abstract headcount into specific people with different needs, so the space mix has a defence.",
     "Who we are designing for",
     "4-6 personas orbiting a core: photo, role, work pattern, what they need from the space.",
     "orbit", "standard",
     "Department and role breakdown", "Persona photos; per-persona day-in-the-life",
     "R", "people", "user-profiles work-styles privacy-inclusion",
     "The orbit layout was built for exactly this."),

    ("S016", "01", "Work Styles Mix",
     "Show that one desk type cannot serve the whole organisation — the argument every varied setting later depends on.",
     "How work actually happens here",
     "The split across focused / collaborative / social / hybrid / mobile / meeting-heavy, with percentages.",
     "concept", "standard",
     "Work-style split (survey or assumed)", "Per-department breakdown",
     "O", "people", "work-styles",
     "State plainly whether the split is measured or assumed — clients notice, and assumed splits get challenged."),

    ("S017", "01", "Headcount & Growth",
     "Fix the number the plan is sized against, and the growth it must absorb without a rebuild.",
     "Headcount and growth",
     "Current headcount, day-one, year-3 and year-5 projections, per department.",
     "title-stats", "standard",
     "Current and projected headcount", "Department-wise split; attrition assumptions",
     "M", "space-planning", "capacity-density flexibility",
     "Growth assumptions belong on the slide, not in the appendix. They are the whole basis of the area."),

    ("S018", "01", "Attendance & Utilisation",
     "Justify any desk-sharing ratio with observed data instead of an assertion.",
     "How full is the office, really?",
     "Attendance by day of week, peak vs average occupancy, historic utilisation, the ratio it supports.",
     "title-stats", "standard",
     "Attendance or badge data", "Utilisation study; booking-system data",
     "O", "space-planning", "capacity-density",
     "Without real data do not propose a sharing ratio. An unbacked ratio is the fastest way to lose the room."),

    ("S019", "01", "Employee Journey",
     "Walk the client through a day in the space so gaps are noticed before they are built.",
     "A day in the workplace",
     "Arrival, orientation, work, meetings, breaks, social, departure — as a sequence.",
     "merge-diagram", "standard",
     "Journey stages", "Per-stage pain points from the current office",
     "O", "people", "employee-experience visitor-experience",
     "Strongest when contrasted against the pain points of the current office."),

    ("S020", "01", "Benchmarks & References",
     "Calibrate expectations against comparable workplaces before proposing anything.",
     "Benchmarks", "3-4 comparable projects with the metric that matters — density, ratio, cost or area per person.",
     "concept", "standard",
     "Benchmark projects and figures", "Images of each benchmark",
     "O", "economics-operations", "cost-per-seat",
     "Benchmarks must match typology and city to be credible."),

    ("S021", "01", "Design Brief Summary",
     "Close the understanding section with the agreed brief — the thing the rest of the deck answers.",
     "What we are solving for",
     "Left: the constraints and givens. Right: the objectives design must deliver.",
     "two-content", "standard",
     "Agreed objectives; constraints", "Priority ranking across objectives",
     "O", "people", "employee-experience",
     "Get explicit agreement here. Every later disagreement traces back to a skipped sign-off on this slide."),

    # === 02 · Site & Context ===============================================
    ("S030", "02", "Section Divider - Site",
     "Mark the shift from brief to the physical building.",
     "Site and context", "Numeral, section title, framing question.",
     "title-slide", "section-starter", "Section number", "",
     "O", "space-planning", "",
     ""),

    ("S031", "02", "Site Locus / Location",
     "Place the office in its city and building, and surface what the location gives and costs.",
     "Where it sits",
     "Locus map, a reveal photo of the building/floor, address, compass and sun path.",
     "site-locus", "standard",
     "Locus map; building photo; address", "Sun-path diagram; neighbourhood amenities",
     "R", "environmental", "daylight-views",
     "The site-locus layout already has the hover-reveal and compass built in."),

    ("S032", "02", "Building & Floor Plate",
     "Show the plate everyone will be reasoning about: core position, column grid, depth, glazing.",
     "The floor plate",
     "Annotated plate with core, columns, structural grid, glazing lines and floor-to-ceiling height.",
     "concept", "standard",
     "Floor plan from the landlord or survey", "Column grid dimensions; slab-to-slab height",
     "R", "space-planning", "zoning circulation",
     "Set `visual: 'image'` so the plan fills the right half rather than the generated diagram."),

    ("S033", "02", "Existing Condition Survey",
     "Record what is there now — the baseline for a refurbishment, and the evidence for what must go.",
     "Existing conditions",
     "Survey photos on a key plan, each hotspot opening the photos for that area.",
     "linked-views", "standard",
     "Site survey photos; key plan", "Dilapidation notes; services condition report",
     "O", "space-planning", "",
     "Use hotspots with galleries so each area's photos open in place. Mandatory for refurbishment, meaningless for greenfield."),

    ("S034", "02", "Constraints & Opportunities",
     "State honestly what the building will not allow, next to what it uniquely offers — credibility comes from naming both.",
     "Constraints and opportunities",
     "Left: constraints (core position, low ceiling, single access, services). Right: opportunities (aspect, terrace, height, daylight).",
     "two-content", "standard",
     "Site observations", "Landlord fit-out guide; base-build drawings",
     "R", "space-planning", "zoning flexibility",
     "Naming constraints early makes the later plan read as resolution rather than compromise."),

    ("S035", "02", "Daylight & Orientation",
     "Justify where the open plan and the enclosed rooms go, using the sun rather than preference.",
     "Daylight and orientation",
     "Sun path across the plate, glare risk zones, the daylight-driven planning rule that follows.",
     "site-locus", "standard",
     "Floor plan; building orientation", "Daylight simulation; glare study",
     "O", "environmental", "daylight-views thermal-comfort",
     "The planning rule is the point: perimeter for people, core for rooms — or the reasoned exception."),

    ("S036", "02", "Base Build & Services Review",
     "Confirm what the base build provides so later MEP scope is not a surprise.",
     "Base build and services",
     "HVAC provision, power availability, fire systems, lift and washroom cores, what the fit-out must add.",
     "title-content", "standard",
     "Base-build services drawings", "Landlord fit-out guide; capacity figures",
     "O", "technology", "power-data",
     "Insufficient base-build capacity is the most common late cost shock — flag any shortfall here, in writing."),

    # === 03 · Strategy & Concept ===========================================
    ("S040", "03", "Section Divider - Approach",
     "Mark the shift from analysis to proposal.",
     "Our approach", "Numeral, section title, framing question.",
     "title-slide", "section-starter", "Section number", "",
     "R", "", "",
     ""),

    ("S041", "03", "Design Approach / Process",
     "Show that the design follows a repeatable method, not inspiration — this is what de-risks the commission.",
     "A practical design sequence",
     "The six steps — Understand, Analyse, Strategise, Design, Test, Resolve — converging on a resolved workplace.",
     "merge-diagram", "standard",
     "", "Client-side milestones mapped onto each step",
     "R", "", "",
     "designSequenceSlide() in src/lib/conceptSlides.ts already builds this from DESIGN_SEQUENCE."),

    ("S042", "03", "Design Concept - The Big Idea",
     "State the single governing idea in one sentence, full-bleed, so the rest of the deck can be judged against it.",
     "{concept_statement}", "One sentence. No supporting points, no image competing with it.",
     "title-only", "section-starter",
     "The concept statement", "A background image at low opacity",
     "M", "experience-brand", "brand-expression placemaking",
     "If it needs two sentences it is not yet a concept. Rewrite until it fits in one."),

    ("S043", "03", "Concept Narrative",
     "Unpack the big idea into the handful of moves that deliver it.",
     "{concept_name}", "Lead line, 3-5 scannable points, one supporting visual.",
     "concept", "standard",
     "Concept narrative; a concept image", "Diagram of the concept logic",
     "M", "experience-brand", "brand-expression storytelling placemaking",
     "This is the standard conceptSlide() shape — lead plus points plus image slot."),

    ("S044", "03", "Mood Board",
     "Set the visual register before any specific room is shown, so renders land as expected rather than as a surprise.",
     "The feeling", "9-12 reference images in a grid: material, light, texture, spatial character.",
     "concept", "design",
     "Reference images", "Per-image caption naming what it is being referenced for",
     "R", "experience-brand", "materiality placemaking",
     "GAP: no image-grid layout. freeform works but every image is placed by hand."),

    ("S045", "03", "Design Cues / Keywords",
     "Bridge from the client's brand and aspirations to the design language, so the leap is visible and traceable.",
     "Design cues", "Keywords paired with the aspiration and brand element each one derives from.",
     "freeform", "standard",
     "Design keywords", "Source imagery per cue",
     "O", "experience-brand", "brand-expression materiality",
     "Pattern exists as ECOM_SLIDE_3_ELEMENTS — explicitly the 'bringing aspiration and brand together' slide."),

    ("S046", "03", "Concept Applied - Option Compare",
     "Let the client see the concept against the alternative, and choose rather than merely accept.",
     "Option A / Option B", "Two treatments of the same space, revealed by a draggable slider.",
     "material-compare", "standard",
     "Two comparable images", "A label per option",
     "O", "experience-brand", "materiality",
     "Also the right layout for refurbishment before/after."),

    ("S047", "03", "Design Principles",
     "Give the client a short rulebook they can hold later decisions against.",
     "Design principles", "4-6 principles, one line each, written as testable rules.",
     "merge-diagram", "standard",
     "Principle list", "An example of each applied",
     "O", "experience-brand", "placemaking",
     "Write them so a later decision can actually fail one. 'Daylight for people, core for rooms' passes that test; 'thoughtful design' does not."),

    ("S048", "03", "Workplace Strategy Model",
     "Name the operating model — assigned, shared, activity-based or hybrid — because everything downstream depends on it.",
     "How the workplace will work",
     "The chosen model, the ratio it implies, what it requires of people and of technology.",
     "concept", "standard",
     "Chosen workplace model", "Change-management outline; booking-tool choice",
     "O", "work-settings", "focused-work collaboration informal-collaboration",
     "Any model other than fully-assigned needs a change-management commitment on this slide, or it will not survive contact with staff."),

    ("S049", "03", "Space Standards / Kit of Parts",
     "Fix the repeatable components once, so the plan is consistent and the BOQ is predictable.",
     "Kit of parts",
     "Workstation sizes, cabin grades, room types, with dimensions and quantities.",
     "title-content", "standard",
     "Space standards schedule", "Dimensioned typical layouts",
     "O", "flexibility-adaptability", "modular-planning multi-purpose-spaces",
     "Essential for GCCs conforming to a global standard and for operators repeating a centre format."),

    ("S050", "03", "Concept-to-Space Map",
     "Show where each concept move actually lands on the plan, so the concept reads as a plan and not as a poster.",
     "Concept, applied", "Key plan with hotspots; each opens the concept driving that space.",
     "linked-views", "standard",
     "Key plan; concept-to-zone mapping", "Per-zone concept summary",
     "O", "experience-brand", "placemaking storytelling",
     "Use ViewHotspot.spaceDetail.concept — this is precisely what the space-detail overlay was built for."),

    # === 04 · Planning =====================================================
    ("S060", "04", "Section Divider - Planning",
     "Mark the shift from idea to plan.",
     "The plan", "Numeral, section title, framing question.",
     "title-slide", "section-starter", "Section number", "",
     "R", "space-planning", "",
     ""),

    ("S061", "04", "Space Programme / Area Statement",
     "Account for every square foot — the slide procurement and finance will actually read.",
     "Area statement",
     "Zone, space type, quantity, unit area, total area, percentage of the plate, with a grand total.",
     "linked-views", "standard",
     "Area programme", "Benchmark comparison per line",
     "M", "space-planning", "capacity-density",
     "GAP: no standalone table layout. Today this rides on LinkedView.seatingZones, which forces it next to a plan."),

    ("S062", "04", "Zoning Strategy",
     "Show the floor resolved into zones before any furniture, so the logic is judged on its own.",
     "Zoning", "Colour-coded zones over the plate, with the adjacency logic stated.",
     "linked-views", "standard",
     "Floor plan; zoning overlay", "Per-zone area and headcount",
     "M", "space-planning", "zoning access-hierarchy adjacency",
     "Use LinkedViewStage to switch between Zoning and Layout on one image — that is what stages are for."),

    ("S063", "04", "Adjacency Diagram",
     "Justify what sits next to what, from interaction frequency rather than convenience.",
     "Adjacencies", "Bubble or matrix diagram of departments, weighted by interaction frequency.",
     "merge-diagram", "standard",
     "Department interaction data", "Interaction frequency survey",
     "R", "function-workflow", "department-interaction movement-workflow",
     "Strongest when backed by an actual interaction survey rather than an org chart."),

    ("S064", "04", "Circulation Strategy",
     "Show that people can move without walking through someone else's concentration.",
     "Circulation", "Primary and secondary routes over the plan, with egress distances and pinch points.",
     "linked-views", "standard",
     "Floor plan; circulation overlay", "Egress distances; footfall estimates",
     "R", "space-planning", "circulation",
     "Overlay egress compliance here and the fire-safety slide gets much shorter."),

    ("S065", "04", "Key Plan / Floor Plate",
     "Give the audience the reference plan every later slide will point back to.",
     "Key plan", "The full plan, labelled, with a legend and north point.",
     "linked-views", "standard",
     "Final floor plan", "Room numbering; a legend",
     "M", "space-planning", "zoning",
     "This is the view every hotspot and key-plan crop later refers to. Establish it once, clearly."),

    ("S066", "04", "Furniture Layout Plan",
     "Prove the headcount actually fits, at real furniture dimensions.",
     "Furniture layout", "Fully furnished plan with workstation counts per zone.",
     "linked-views", "standard",
     "Furniture layout drawing", "Per-zone counts; furniture legend",
     "M", "space-planning", "capacity-density",
     "The count on this plan must match the area statement exactly. A mismatch is noticed immediately."),

    ("S067", "04", "Seating Capacity / Occupancy",
     "Reconcile what was required against what was achieved, zone by zone — the number the client checks hardest.",
     "Seating capacity - achieved {achieved_count} pax",
     "Zone-grouped Area / Required / Achieved table beside the plan, hover-linked to the hotspots.",
     "linked-views", "standard",
     "Required and achieved counts per zone; key plan", "Notes per row; Excel import of the capacity sheet",
     "M", "space-planning", "capacity-density",
     "Fully built: LinkedView.seatingZones with two-way hover, plus Excel import via parseSeatingWorkbook."),

    ("S068", "04", "Workstation Mix & Ratios",
     "Explain the desk mix and the sharing ratio in one place, with the data behind it.",
     "Workstation mix", "Counts by workstation type, the sharing ratio, and sq ft per person.",
     "title-stats", "standard",
     "Workstation counts by type", "Sharing ratio; benchmark comparison",
     "R", "space-planning", "capacity-density flexibility",
     "Tie the ratio back to the attendance slide, or it reads as an assumption."),

    ("S069", "04", "Meeting Room Mix",
     "Show the meeting rooms were sized from meeting patterns, not from habit.",
     "Meeting room mix", "Rooms by capacity band, seats-per-head ratio, the booking data behind it.",
     "title-stats", "standard",
     "Meeting room schedule", "Meeting-pattern or calendar data",
     "O", "work-settings", "formal-meetings meeting-patterns phone-video-calls",
     "Calendar data almost always shows too many large rooms and too few 2-4 person ones. Say so."),

    ("S070", "04", "Stacking Plan",
     "Resolve which department sits on which floor before anyone argues about desks.",
     "Stacking", "Floor-by-floor department allocation with headcount per floor.",
     "linked-views", "standard",
     "Floor allocation; headcount per floor", "Vertical circulation strategy",
     "O", "space-planning", "adjacency zoning",
     "Only meaningful for multi-floor projects — suppress it entirely on single-floor ones."),

    ("S071", "04", "Zone Walkthrough",
     "Let the client interrogate the plan live — click any space and see the concept, render and occupancy that justify it.",
     "Explore the plan", "Key plan with a hotspot per space; each opens concept, renders, walkthrough and occupancy.",
     "linked-views", "standard",
     "Key plan; per-zone renders", "Per-zone walkthrough video; concept summary; BOQ note",
     "R", "space-planning", "zoning adjacency",
     "Fully built: ViewHotspot.spaceDetail plus SpaceDetailOverlay. The strongest live-pitch moment in the product."),

    # === 05 · Design - Space by Space ======================================
    # The section where typology bites hardest: the space LIST itself changes.
    # S094-S100 are typology-gated and are excluded outright from most decks.

    ("S080", "05", "Section Divider - Design",
     "Mark the shift from plan to experience.",
     "The design", "Numeral, section title, framing question.",
     "title-slide", "section-starter", "Section number", "",
     "R", "experience-brand", "",
     ""),

    ("S081", "05", "Reception & Arrival",
     "Show the first thirty seconds of the building — the only space every visitor will judge.",
     "Reception", "Hero render, arrival sequence, reception desk, branding, seating, security interface.",
     "title-content", "design",
     "Reception render", "Material callouts; a second angle; branding detail",
     "M", "experience-brand", "arrival brand-expression",
     "Always the strongest render in the deck. If only one image is ready, it should be this one."),

    ("S082", "05", "Client Waiting / Lounge",
     "Show where visitors wait, and that waiting is not an afterthought.",
     "Visitor lounge", "Render, seating arrangement, refreshment provision, acoustic and visual separation from staff.",
     "title-content", "design",
     "Lounge render", "Furniture specification; material callouts",
     "O", "people", "visitor-experience",
     "Escalate where the client suite is the commercial point of the office."),

    ("S083", "05", "Open Workspace / Workhall",
     "Show where most people spend most of their time — the space the fit-out is really for.",
     "Workspace", "Render, workstation type, desk spacing, storage, daylight access, acoustic treatment.",
     "title-content", "design",
     "Workhall render", "Workstation detail; a second angle; dimensions",
     "M", "work-settings", "focused-work collaboration",
     "Show it at realistic occupancy. An empty workhall render invites doubt about whether it actually fits."),

    ("S084", "05", "Cabins & Leadership",
     "Resolve the hierarchy question visually before it is negotiated person by person.",
     "Cabins and leadership offices", "Render, cabin grades and sizes, glazing and privacy treatment, storage.",
     "title-content", "design",
     "Cabin render", "Cabin-grade schedule; dimensions",
     "R", "people", "privacy-inclusion",
     "Show the grades as a published rule. Ad-hoc cabin sizing is where fit-out programmes go to die."),

    ("S085", "05", "Meeting Rooms",
     "Show the everyday rooms in the mix and the AV standard each one carries.",
     "Meeting rooms", "Renders of 2-3 room sizes, table configuration, AV, acoustic and glazing treatment.",
     "title-content", "design",
     "Meeting room render", "AV specification; acoustic ratings",
     "M", "work-settings", "formal-meetings phone-video-calls",
     "State the AV standard per size band here and the technology slide gets much shorter."),

    ("S086", "05", "Boardroom",
     "Show the room where the company's most consequential meetings happen.",
     "Boardroom", "Hero render, table, AV and video-conference setup, acoustic privacy, materiality.",
     "title-content", "design",
     "Boardroom render", "AV specification; a second angle; material detail",
     "O", "work-settings", "formal-meetings",
     "Usually the second-highest-value render after reception. Premium and above, it is mandatory."),

    ("S087", "05", "Huddle & Phone Booths",
     "Show where calls happen, which is the single most common complaint in every open-plan office.",
     "Huddle rooms and phone booths", "Render, quantity and distribution, acoustic rating, ventilation and power.",
     "title-content", "design",
     "Booth render or product image", "Acoustic ratings; distribution on plan",
     "O", "work-settings", "phone-video-calls informal-collaboration",
     "Quantity matters more than appearance. Give the booths-per-100-seat ratio explicitly."),

    ("S088", "05", "Collaboration & Breakout",
     "Show the informal settings that make the desk count defensible.",
     "Collaboration and breakout", "Render, settings variety, writable and display surfaces, power, acoustic zoning.",
     "title-content", "design",
     "Breakout render", "Settings menu; furniture specification",
     "R", "work-settings", "informal-collaboration social-breakout collaboration",
     "Escalates to mandatory under the Collaborative (ABW) concept — it is the concept's main evidence."),

    ("S089", "05", "Cafeteria & Pantry",
     "Show the space that carries the most people per square foot and most of the social life.",
     "Cafeteria", "Render, seating capacity, servery and pantry provision, peak-load sizing, dual use as town hall.",
     "title-content", "design",
     "Cafeteria render", "Seating count; peak-load calculation; servery detail",
     "M", "work-settings", "social-breakout",
     "Size for the peak sitting, not the average. Shift-based workplaces need the overlap number."),

    ("S090", "05", "Training / Town Hall",
     "Show where the whole office gathers, and prove the room can actually hold them.",
     "Training and town hall", "Render, capacity in each configuration, AV and acoustics, operable partition strategy.",
     "title-content", "design",
     "Training room render", "Capacity per configuration; AV specification",
     "O", "work-settings", "training-multipurpose",
     "Multi-configuration capacity is the point. Show at least two layouts of the same room."),

    ("S091", "05", "Wellness & Mother's Room",
     "Show the provision that signals the workplace takes care seriously — and which is often a statutory requirement.",
     "Wellness rooms", "Render, mother's room, quiet and prayer rooms, first aid, privacy and access control.",
     "title-content", "design",
     "Wellness room render", "Provision schedule; statutory requirement reference",
     "O", "wellbeing", "mental-recharge social-wellbeing user-control",
     "A mother's room is statutory at most Indian workplace sizes — check the threshold and state it."),

    ("S092", "05", "Washrooms",
     "Show the provision, the fixture count and the accessibility compliance.",
     "Washrooms", "Render, fixture count against code, accessible provision, material and maintenance strategy.",
     "title-content", "design",
     "Washroom render or fixture schedule", "Code compliance calculation",
     "O", "safety-compliance", "accessibility",
     "Often landlord-provided. Include only where the fit-out actually covers it."),

    ("S093", "05", "Support, Utility & Server",
     "Account for back-of-house so it is not discovered as a shortfall on site.",
     "Support and utility", "Print and copy, storage, lockers, housekeeping, UPS and server, with areas.",
     "title-content", "design",
     "Support space schedule", "Server room services requirement",
     "O", "function-workflow", "support-spaces storage",
     "Under-provisioned back-of-house is the most common post-handover complaint. Give it real numbers."),

    ("S094", "05", "Trading / Dealing Floor",
     "Show the specialist floor that drives the power, cooling, acoustic and compliance load of the whole project.",
     "Dealing floor", "Render, desk configuration, screen arrangement, power and cooling, acoustic and recording compliance.",
     "title-content", "design",
     "Dealing floor render; desk specification", "Power and cooling load; compliance requirement",
     "O", "technology", "power-data av-hybrid-work",
     "BFSI only. Services load here typically governs the entire electrical design."),

    ("S095", "05", "Lab / Workshop Interface",
     "Show where office meets lab — the boundary that governs services, access and safety.",
     "Lab interface", "Render, transition and gowning zone, visual connection, services and access control boundary.",
     "title-content", "design",
     "Lab interface render; lab adjacency", "Services load; access control zoning",
     "O", "safety-compliance", "security life-safety",
     "R&D, pharma and life sciences only. Confirm services capacity before committing to any adjacency."),

    ("S096", "05", "Studio / Content Space",
     "Show the production space that doubles as the brand's own set.",
     "Content studio", "Render, shoot setup, lighting rig, acoustic treatment, edit suite adjacency, storage.",
     "title-content", "design",
     "Studio render", "Lighting and AV specification; acoustic ratings",
     "O", "technology", "av-hybrid-work",
     "Media, creative and D2C only. Acoustic isolation from the open plan is the hard part."),

    ("S097", "05", "Community & Event Space",
     "Show the space that carries an operator's community programme and its events revenue.",
     "Community space", "Render, event configurations, capacity per setup, bar or servery, AV, after-hours access.",
     "title-content", "design",
     "Community space render", "Capacity per configuration; AV specification",
     "O", "work-settings", "social-breakout training-multipurpose",
     "Managed-workspace operators only, where it is mandatory — it is a revenue line, not an amenity."),

    ("S098", "05", "Experience / Demo Zone",
     "Show the curated visitor journey that is the entire point of a showcase space.",
     "Experience zone", "Render, the visitor route, demo stations, AV and immersion, dwell times, reveal sequence.",
     "title-content", "design",
     "Experience zone render; visitor route", "AV specification; content plan; dwell timings",
     "O", "experience-brand", "storytelling placemaking",
     "Experience centres and innovation hubs only. Sequence carries more weight here than any single render."),

    ("S099", "05", "Operations Control Tower",
     "Show the 24x7 nerve centre and what running it around the clock demands.",
     "Control tower", "Render, screen wall, desk configuration, shift handover space, 24x7 amenity provision.",
     "title-content", "design",
     "Control room render", "Screen wall specification; shift pattern",
     "O", "technology", "av-hybrid-work smart-workplace",
     "E-commerce and logistics only. Size the amenities for shift overlap, not for headcount."),

    ("S100", "05", "Public Interface Counter",
     "Show where the public is received and served, and how they are kept separate from staff areas.",
     "Public interface", "Render, counter arrangement, queuing and waiting, accessibility, staff-side separation.",
     "title-content", "design",
     "Public counter render", "Queuing calculation; accessibility compliance",
     "O", "people", "visitor-experience",
     "Government, PSU and institutional only. Queue length and accessible counter height are the checkable items."),

    # === 06 · Materials & Detail ===========================================
    ("S110", "06", "Section Divider - Materials",
     "Mark the shift from space to substance.",
     "Materials and detail", "Numeral, section title, framing question.",
     "title-slide", "section-starter", "Section number", "",
     "O", "experience-brand", "",
     ""),

    ("S111", "06", "Material Palette",
     "Fix what the workplace is made of, so renders can be trusted and the BOQ has a basis.",
     "Material palette", "Material swatches with names, application, finish and maintenance note.",
     "concept", "design",
     "Material swatch images; material schedule", "Supplier references; maintenance regime",
     "M", "experience-brand", "materiality",
     "Name application per material. An unlabelled swatch board is decoration, not a specification."),

    ("S112", "06", "Colour Palette",
     "Fix the colour logic and its relationship to the client's brand.",
     "Colour", "Primary, secondary and accent colours, where each is applied, brand derivation.",
     "concept", "standard",
     "Colour palette", "Brand colour reference; application map",
     "O", "experience-brand", "brand-expression",
     "Tie every colour back to the brand landscape slide, or it reads as arbitrary."),

    ("S113", "06", "Furniture Selection",
     "Show the actual furniture, since it is what people touch and a large share of the budget.",
     "Furniture", "Product images by category, with dimensions, finish and ergonomic specification.",
     "concept", "standard",
     "Furniture product images; specification", "Supplier and lead time; alternates",
     "O", "wellbeing", "ergonomics",
     "Lead times belong here, not only on the programme slide — furniture is the usual critical path."),

    ("S114", "06", "Lighting Design",
     "Show the light, because it governs how every render will actually look when built.",
     "Lighting", "Ambient, task and feature layers, fitting selection, lux levels, controls.",
     "concept", "standard",
     "Lighting layout; fitting selection", "Lux calculations; control strategy",
     "R", "environmental", "lighting daylight-views",
     "Lux targets per zone make this checkable rather than decorative."),

    ("S115", "06", "Acoustic Strategy",
     "Show how the open plan will be survivable, which is the most common cause of post-handover complaint.",
     "Acoustics", "Ceiling and wall treatments, partition ratings, masking, planning-level separation.",
     "concept", "standard",
     "Acoustic treatment schedule", "NRC and STC ratings; acoustic zoning plan",
     "O", "environmental", "acoustics",
     "Escalates to mandatory under Industrial/Raw, where exposed soffits remove the usual absorption."),

    ("S116", "06", "Signage & Wayfinding",
     "Show that people can find their way without being escorted.",
     "Wayfinding", "Signage family, hierarchy, typography, materials, key locations on plan.",
     "concept", "standard",
     "Signage design", "Signage location plan; typography specification",
     "O", "experience-brand", "placemaking brand-expression",
     "Escalates on large floor plates and anywhere the public is received."),

    ("S117", "06", "Graphics & Storytelling",
     "Use the walls to say something specific about this company rather than a stock motivational line.",
     "Graphics and storytelling", "Graphic locations, content themes, the story each wall carries, materials.",
     "concept", "standard",
     "Graphic concepts", "Content plan; heritage or archive material",
     "O", "experience-brand", "storytelling brand-expression",
     "Content sourcing is usually the bottleneck. Name who supplies it and by when."),

    ("S118", "06", "Planting & Greenscaping",
     "Show the planting as a designed, maintained system rather than pots added at handover.",
     "Planting", "Species by condition, planter design, locations on plan, irrigation and maintenance.",
     "concept", "standard",
     "Planting plan; species selection", "Irrigation strategy; maintenance contract scope",
     "O", "environmental", "biophilia",
     "Mandatory under the Biophilic concept. Always state who maintains it and how often."),

    ("S119", "06", "Art Programme",
     "Show the commissioned pieces, which at flagship grade carry much of the identity.",
     "Art", "Pieces and locations, artists, commissioning approach, budget allocation.",
     "concept", "design",
     "Art references or commissions", "Artist profiles; budget allocation",
     "O", "experience-brand", "storytelling placemaking",
     "Luxury flagship and Heritage projects. Commissioning lead times are long — put them on the programme."),

    ("S120", "06", "Ceiling & Flooring",
     "Fix the two largest continuous surfaces, which set the acoustic and maintenance baseline.",
     "Ceiling and flooring", "Ceiling systems and heights by zone, floor finishes by zone, transitions.",
     "concept", "standard",
     "Ceiling and flooring schedule", "Reflected ceiling plan; transition details",
     "O", "environmental", "acoustics",
     "Heights per zone matter more than the finish. Show them where the plate is tight."),

    ("S121", "06", "Detail Junctions",
     "Show that the detailing has been resolved, not left to the site to invent.",
     "Details", "Key junction details: skirting, reveals, glazing, ceiling perimeter, joinery edges.",
     "concept", "standard",
     "Detail drawings", "3D detail views",
     "O", "experience-brand", "materiality",
     "Premium and above, where the junction quality is most of what is being paid for."),

    # === 07 · Technical & Compliance =======================================
    ("S130", "07", "Section Divider - Technical",
     "Mark the shift from appearance to performance.",
     "Technical", "Numeral, section title, framing question.",
     "title-slide", "section-starter", "Section number", "",
     "O", "technology", "",
     ""),

    ("S131", "07", "MEP & Services Coordination",
     "Show the services are coordinated with the architecture rather than discovered to clash on site.",
     "Services coordination", "HVAC zoning, electrical distribution, plumbing, fire systems, ceiling coordination.",
     "title-content", "standard",
     "MEP scope; base-build capacity", "Coordinated services drawings; load calculations",
     "O", "technology", "power-data",
     "Name any base-build capacity shortfall explicitly. This is where late cost shocks originate."),

    ("S132", "07", "AV & Technology Standard",
     "Fix what technology every room type gets, so nothing is negotiated room by room during delivery.",
     "AV standard", "Room-type-by-room-type AV specification, display sizes, camera, audio, control.",
     "concept", "standard",
     "AV specification by room type", "Platform standard; integration requirements",
     "O", "technology", "av-hybrid-work connectivity",
     "Mandatory for GCCs — the parent's platform standard usually dictates it entirely."),

    ("S133", "07", "IT, Power & Data",
     "Show the infrastructure that everything else depends on.",
     "Power and data", "Power distribution, data cabling, wifi coverage, UPS and server provision, charging.",
     "title-content", "standard",
     "Power and data requirements", "Server room specification; wifi heat map",
     "O", "technology", "power-data connectivity",
     "Redundancy requirements belong here for GCC, BFSI and 24x7 operations."),

    ("S134", "07", "Smart Workplace",
     "Show the sensing and booking layer, and be explicit about what it does with people's data.",
     "Smart workplace", "Room booking, occupancy sensing, digital wayfinding, analytics, the privacy position.",
     "concept", "standard",
     "Smart workplace scope", "Platform selection; data and privacy policy",
     "O", "technology", "smart-workplace future-technology",
     "Occupancy sensing is a privacy conversation. Involve HR and Legal before it is specified, and say so here."),

    ("S135", "07", "Fire & Life Safety",
     "Show compliance, because it can veto the plan and usually arrives late.",
     "Fire and life safety", "Egress routes and travel distances, detection and suppression, compartmentation, refuge.",
     "title-content", "standard",
     "Fire strategy; egress calculations", "Approval status; consultant sign-off",
     "R", "safety-compliance", "life-safety emergency-planning",
     "If the circulation slide already carries egress distances, this slide can be short."),

    ("S136", "07", "Accessibility",
     "Show the workplace works for everyone, and meets the standard it is held to.",
     "Accessibility", "Accessible routes, door widths, clearances, accessible washrooms and furniture, signage.",
     "title-content", "standard",
     "Accessibility compliance review", "Standard being applied; audit results",
     "R", "safety-compliance", "accessibility",
     "Name the standard being applied. 'Accessible' without a named standard is unverifiable."),

    ("S137", "07", "Security & Access Control",
     "Show the access hierarchy, from public through staff to restricted.",
     "Security and access", "Zones by access level on plan, control points, visitor management, CCTV coverage.",
     "linked-views", "standard",
     "Access control zoning; key plan", "CCTV layout; visitor management process",
     "O", "safety-compliance", "security",
     "Mandatory for BFSI, R&D and GCC. Show it as a zoning overlay, not as a list."),

    ("S138", "07", "Sustainability Approach",
     "Show environmental performance as a design position rather than a disclaimer.",
     "Sustainability", "Material selection, energy and water strategy, reuse, waste and indoor health.",
     "concept", "standard",
     "Sustainability strategy", "Certification target; material provenance data",
     "O", "sustainability", "material-selection energy reuse-refurbishment indoor-health",
     "Escalates to mandatory under the Sustainable/Certified Green concept."),

    ("S139", "07", "Green Certification Pathway",
     "Commit to a rating and show the credits that get there.",
     "Certification pathway", "Target rating, credit scorecard, gaps, what the client must do and by when.",
     "title-stats", "standard",
     "Target certification and level", "Credit-by-credit scorecard; consultant appointment",
     "O", "sustainability", "energy water waste-circularity indoor-health",
     "Certification changes programme and budget. Commit early or do not claim it at all."),

    # === 08 · Commercials & Delivery =======================================
    ("S150", "08", "Section Divider - Commercials",
     "Mark the shift from design to money and time.",
     "Commercials and delivery", "Numeral, section title, framing question.",
     "title-slide", "section-starter", "Section number", "",
     "R", "economics-operations", "",
     ""),

    ("S151", "08", "Budget Summary",
     "Show the number, broken down enough to be interrogated.",
     "Budget", "Cost by package — civil, joinery, MEP, furniture, AV, other — with totals and a contingency line.",
     "title-stats", "standard",
     "Cost estimate by package", "Benchmark comparison; contingency assumptions",
     "M", "economics-operations", "budget",
     "GAP: no cost-table layout. title-stats handles 3-4 headline figures but not a full package breakdown."),

    ("S152", "08", "Cost per Seat",
     "Give the one figure that travels — the number quoted in the meeting the client has after this one.",
     "{cost_per_seat} per seat", "The figure, what it includes and excludes, and the benchmark band.",
     "stat-hero", "standard",
     "Cost per seat", "Benchmark range; inclusions and exclusions list",
     "R", "economics-operations", "cost-per-seat",
     "Always state inclusions. A cost-per-seat without them is meaningless and will be misquoted."),

    ("S153", "08", "BOQ Highlights",
     "Surface the line items that actually move the number, rather than the whole schedule.",
     "Where the money goes", "The top 10-15 lines by value, with quantity, rate and total.",
     "title-content", "standard",
     "BOQ", "Rate basis; alternates",
     "O", "economics-operations", "budget lifecycle-cost",
     "GAP: no line-item table layout. SpaceBoq exists as a placeholder type only — the real table is unbuilt."),

    ("S154", "08", "Value Engineering Options",
     "Give the client levers to pull if the number is too high, before they start cutting arbitrarily.",
     "Value engineering options", "Option, saving, and what is given up — so the trade-off is explicit.",
     "two-content", "standard",
     "VE options with savings", "Impact assessment per option",
     "O", "economics-operations", "budget durability",
     "GAP: no comparison-table layout. Always state what is lost; a saving without a cost reads as padding."),

    ("S155", "08", "Project Timeline",
     "Show when it will be finished and what has to happen for that to hold.",
     "Programme", "Phases from design through handover, with milestones, dependencies and the critical path.",
     "merge-diagram", "standard",
     "Project programme", "Critical path; client-side decision dates",
     "M", "economics-operations", "operational-efficiency",
     "GAP: no timeline or Gantt layout. merge-diagram shows sequence but neither duration nor overlap."),

    ("S156", "08", "Delivery Model & Team",
     "Show who does what, and who the client calls when something goes wrong.",
     "How we deliver", "Team structure, roles, reporting lines, governance rhythm, escalation path.",
     "merge-diagram", "standard",
     "Delivery team structure", "Named individuals; governance calendar",
     "R", "economics-operations", "operational-efficiency",
     "Name the single point of contact. It is the thing clients most want from this slide."),

    ("S157", "08", "Site Safety & Quality",
     "Show how the site will be run, which matters most where work happens in a live building.",
     "Safety and quality on site", "Safety protocol, quality checkpoints, inspection regime, snagging process.",
     "title-content", "standard",
     "Safety and quality process", "Certifications; inspection schedule",
     "O", "safety-compliance", "life-safety",
     "Escalates for refurbishment in an occupied building, and for plant-attached projects."),

    ("S158", "08", "Operations & Handover",
     "Show what the client receives at handover and how the space is run afterwards.",
     "Handover", "Handover deliverables, O&M manuals, training, soft-landing period, facilities interface.",
     "title-content", "standard",
     "Handover scope", "O&M documentation list; training plan",
     "O", "economics-operations", "operational-efficiency lifecycle-cost",
     "Mandatory for managed-office projects, where the operator has to run it from day one."),

    ("S159", "08", "Warranty & Post-Handover",
     "State what is covered, for how long, and who to call.",
     "Warranty and support", "Warranty periods by element, defects liability, response times, support contact.",
     "title-content", "standard",
     "Warranty terms", "Defects liability period; SLA",
     "O", "economics-operations", "durability lifecycle-cost",
     "Specific periods per element. A blanket '1 year warranty' invites disputes later."),

    ("S160", "08", "Risks & Assumptions",
     "Put the assumptions in writing now, so a later change is a variation rather than an argument.",
     "Risks and assumptions", "Key assumptions, risks with likelihood and mitigation, dependencies on the client.",
     "two-content", "standard",
     "Assumption and risk register", "Mitigation owner per risk",
     "O", "economics-operations", "budget",
     "The most under-used slide in the library and the one that saves the most money."),

    ("S161", "08", "Next Steps",
     "Leave the room with a decision and a date rather than goodwill.",
     "Next steps", "3-5 actions, each with an owner and a date, and what is needed to proceed.",
     "title-only", "standard",
     "Agreed next steps", "Decision dates; approval requirements",
     "M", "", "",
     "Owner and date on every line. A next-steps slide without both is a summary, not a close."),

    ("S162", "08", "Thank You / Contact",
     "Close cleanly, leaving contact details on screen through the Q&A.",
     "Thank you", "Contact details, both logos, one closing image.",
     "title-slide", "section-starter",
     "Contact details; logos", "A closing hero image",
     "M", "", "",
     "This slide stays up during questions — keep contact details legible from the back of the room."),
]
